# Generated by Django 4.2.27 on 2026-01-29 06:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(help_text='Unique airport code (e.g., JFK, LAX, DEL)', max_length=10, unique=True)),
                ('position', models.CharField(help_text='Position identifier in the route network', max_length=50)),
                ('duration', models.IntegerField(help_text='Flight duration in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left', models.ForeignKey(blank=True, help_text='Left child airport in the route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_left', to='airports.airportroute')),
                ('right', models.ForeignKey(blank=True, help_text='Right child airport in the route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_right', to='airports.airportroute')),
            ],
            options={
                'verbose_name': 'Airport Route',
                'verbose_name_plural': 'Airport Routes',
                'ordering': ['airport_code'],
            },
        ),
    ]
